# Generated by Django 4.1.7 on 2023-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="task",
            field=models.ManyToManyField(related_name="tag", to="app.task"),
        ),
    ]
