# Generated by Django 4.1.7 on 2023-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_tag_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["created_at", "is_done"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="is_completed",
            new_name="is_done",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="task",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="app.tag"),
        ),
    ]
