# Generated by Django 4.1.7 on 2023-02-19 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_tag_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "created_at"]},
        ),
    ]
