# Generated by Django 4.1.7 on 2023-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
    ]
